import type { AppLocale } from '@/i18n'

const words = {
  title: ['Template reading', '模板阅读', '模板閱讀'],
  layoutNote: ['Reading view; final Word layout may differ. Images and external links are omitted.', '阅读视图；最终 Word 排版可能不同。图片与外部链接已省略。', '閱讀視圖；最終 Word 排版可能不同。圖片與外部連結已省略。'],
  loading: ['Loading uploaded template…', '正在载入已上传模板…', '正在載入已上傳模板…'],
  notUploaded: ['No {fileKey} template has been uploaded to this project.', '当前项目尚未上传 {fileKey} 标准模板。', '目前項目尚未上傳 {fileKey} 標準模板。'],
  uploadNote: ['Upload the template in step 1 to read and locate its clauses. Your current inputs are kept.', '请在第 1 步上传模板后阅读和定位条款。当前已填写的值会保留。', '請在第 1 步上傳模板後閱讀和定位條款。目前已填寫的值會保留。'],
  upload: ['Go to template upload', '前往上传模板', '前往上傳模板'],
  unsupported: ['Unsupported template format. Upload DOCX or PDF to read this template.', '不支持此模板格式。请上传 DOCX 或 PDF 以阅读模板。', '不支援此模板格式。請上傳 DOCX 或 PDF 以閱讀模板。'],
  failed: ['Could not read the uploaded template.', '无法读取已上传模板。', '無法讀取已上傳模板。'],
  retry: ['Retry', '重试', '重試'],
  pdfLimit: ['PDF reading supports page navigation only; clause text locations are unavailable.', 'PDF 阅读仅支持翻页；无法定位条款文字。', 'PDF 閱讀僅支援翻頁；無法定位條款文字。'],
  exact: ['Exact source location', '准确原文位置', '準確原文位置'],
  approximate: ['Approximate location — check the source', '近似位置 — 请核对原文', '近似位置 — 請核對原文'],
  missing: ['Source location not found', '未找到原文位置', '未找到原文位置'],
  edition: ['Uploaded source differs from the verified catalogue edition. Historical paragraph ranges are not used.', '上传原文与已验证目录版本不同，未使用旧段落范围。', '上傳原文與已驗證目錄版本不同，未使用舊段落範圍。'],
  previous: ['Previous location', '上一个位置', '上一個位置'],
  next: ['Next location', '下一个位置', '下一個位置'],
  locations: ['Source locations', '原文位置', '原文位置'],
  location: ['Location', '位置', '位置'],
  of: ['of', '/', '/'],
  paragraph: ['Paragraph', '段落', '段落'],
  selected: ['Selected input', '当前输入', '目前輸入'],
  currentValue: ['Current value', '当前取值', '目前取值'],
  item: ['item', '项', '項'],
  items: ['items', '项', '項'],
  valueEntries: ['values', '项取值', '項取值'],
  details: ['Details', '其他信息', '其他資訊'],
  noValueItems: ['No items', '无项目', '無項目'],
  invalidValue: ['Unable to display this value. Check the input or original value.', '无法展示此取值，请核对输入项或原始值。', '無法展示此取值，請核對輸入項或原始值。'],
  rawValue: ['Original value', '原始值', '原始值'],
  unknown: ['Unknown', '待确定', '待確定'],
  unsaved: ['Unsaved', '未保存', '未儲存'],
  edit: ['Edit input / review adoption', '编辑输入／复核采用', '編輯輸入／覆核採用'],
  input: ['Return to input', '返回输入项', '返回輸入項'],
  source: ['Source', '来源', '來源'],
  candidates: ['Extraction candidates (not automatically adopted)', '识别候选（不会自动采用）', '識別候選（不會自動採用）'],
  affected: ['Affected document / clause locations', '影响的文件／条款位置', '影響的文件／條款位置'],
  editTarget: ['Edit exact target', '编辑具体目标', '編輯具體目標'],
  select: ['Select input', '选择输入项', '選擇輸入項'],
  choose: ['Choose an input or clause location to navigate the uploaded template.', '选择输入项或条款位置以定位已上传模板。', '選擇輸入項或條款位置以定位已上傳模板。'],
  unmapped: ['Converted layout cannot map this paragraph unambiguously. Current native source text is shown below.', '转换排版无法准确对应此段落。下方显示当前原文段落。', '轉換排版無法準確對應此段落。下方顯示目前原文段落。'],
  changed: ['The source changed while loading. Retry to read one consistent source version.', '载入时原文发生变化。请重试以读取一致的原文版本。', '載入時原文發生變化。請重試以讀取一致的原文版本。'],
  empty: ['No readable document content was found.', '未找到可读的文件内容。', '未找到可讀的文件內容。'],
  true: ['Yes', '是', '是'],
  false: ['No', '否', '否'],
  locate: ['Locate', '定位', '定位']
} as const

export type PreviewWord = keyof typeof words
export const previewWord = (key: PreviewWord, locale: AppLocale): string => words[key][locale === 'en' ? 0 : locale === 'zh-Hant' ? 2 : 1]
