import type { LocalizedText } from '@/api/types'
import type { AppLocale } from '@/i18n'

const triples = {
  businessGraph: ['变量关系图', '變量關係圖', 'Variable relationships'],
  readDocument: ['阅读文稿', '閱讀文稿', 'Read document'],
  draftingField: ['起草输入', '起草輸入', 'Drafting field'],
  chooseBoundField: ['选择输入项或位置标记', '選擇輸入項或位置標記', 'Choose a field or a location marker'],
  boundTargets: ['对应文档位置', '對應文件位置', 'Bound document locations'],
  otherLocations: ['其他位置', '其他位置', 'Other locations'],
  sourceParagraph: ['原稿段落', '原稿段落', 'Source paragraph'],
  pointLocationNote: ['框线标出与目标正文核对一致的文字范围；准星仅表示段落锚点。', '框線標出與目標正文核對一致的文字範圍；準星僅表示段落錨點。', 'Boxes show verified target text ranges; crosshairs indicate paragraph anchors only.'],
  pdfParagraphAnchor: ['仅定位到段落锚点', '僅定位到段落錨點', 'Paragraph anchor only'],
  pdfTextRangeUnavailable: ['尚不能核对此段的完整文字范围，仅定位到段落锚点。', '尚不能核對此段的完整文字範圍，僅定位到段落錨點。', 'The full target text range could not be verified; only its paragraph anchor is available.'],
  appliedTarget: ['已应用采用值', '已套用採用值', 'Adopted value applied'],
  unappliedTarget: ['尚未应用的目标', '尚未套用的目標', 'Unapplied target'],
  unchangedTarget: ['正文未改变', '正文未改變', 'Unchanged target'],
  bodyEditedTarget: ['正文已人工修改', '正文已人工修改', 'Body edited'],
  bodyAddedTarget: ['人工新增段落', '人工新增段落', 'Body paragraph added'],
  generatedAddedTarget: ['生成时新增段落', '產生時新增段落', 'Generated paragraph added'],
  savedDocumentChanges: ['已保存的文档变更', '已儲存的文件變更', 'Saved document changes'],
  documentOperationApplied: ['文档处理已应用', '文件處理已套用', 'Document operation applied'],
  noOriginalTemplateParagraph: ['新增段落没有对应的模板原文。', '新增段落沒有對應的模板原文。', 'No original template paragraph for this addition.'],
  exactBinding: ['标记对应准确', '標記對應準確', 'Exact marker identity'],
  removedBinding: ['该位置已删除', '該位置已刪除', 'Target removed'],
  missingBinding: ['未找到该位置', '未找到該位置', 'Target missing'],
  approximateBinding: ['近似位置，需核对', '近似位置，需核對', 'Approximate location; check the document'],
  conflictedBinding: ['位置对应有冲突', '位置對應有衝突', 'Conflicting target identity'],
  pendingGeometry: ['PDF 位置待生成', 'PDF 位置待產生', 'PDF location pending'],
  unavailableGeometry: ['PDF 点位置不可用', 'PDF 點位置不可用', 'PDF point unavailable'],
  templateTargetText: ['模板目标原文', '模板目標原文', 'Original template target text'],
  savedTargetText: ['已保存目标正文', '已儲存目標正文', 'Saved target text'],
  correspondenceQuotation: ['项目沟通资料引文', '項目溝通資料引文', 'Project correspondence quotation'],
  quotedSourceContext: ['阅读该引文的原始上下文', '閱讀該引文的原始上下文', 'Read the quoted source context'],
  noCorrespondenceQuotation: ['此输入暂无可核对的项目资料引文。', '此輸入暫無可核對的項目資料引文。', 'No project correspondence quotation is available for this input.'],
  sourceContextUnavailable: ['此引文对应版本的上下文暂不可用。', '此引文對應版本的上下文暫不可用。', 'Context for this quotation version is unavailable.'],
  historicalEvidenceContext: ['以下是已留存识别版本的原文；当前资料已有变化。', '以下是已留存識別版本的原文；目前資料已有變化。', 'This is the retained extraction source version; current correspondence has changed.'],
  modelExplanation: ['模型解释', '模型解釋', 'Model explanation'],
  originalTemplate: ['原始模板', '原始模板', 'Original template'],
  savedDraftView: ['已保存文稿', '已儲存文稿', 'Saved draft'],
  bindingLoading: ['正在读取文档位置…', '正在讀取文件位置…', 'Loading document locations…'],
  bindingUnavailable: ['文档位置暂不可用', '文件位置暫不可用', 'Document locations unavailable'],
  noRegisteredResultLocations: ['此保存版本没有可用的已登记段落位置。正文仍可阅读，尚不能声称准确定位。', '此儲存版本沒有可用的已登記段落位置。正文仍可閱讀，尚不能聲稱準確定位。', 'No registered paragraph locations are available for this saved revision. Readable text remains available; no exact mapping is claimed.'],
  noRegisteredSourceLocations: ['此原始模板没有可用的已登记段落位置，尚不能声称准确定位。', '此原始模板沒有可用的已登記段落位置，尚不能聲稱準確定位。', 'No registered paragraph locations are available for this original template. No exact mapping is claimed.'],
  bindingIdentityMismatch: ['文档位置与当前文件版本不一致，请重试。', '文件位置與目前檔案版本不一致，請重試。', 'Document locations do not match the current file version. Retry.'],
  pendingLocations: ['正文尚未保存；保存后再定位对应结果。原稿仍可阅读。', '正文尚未儲存；儲存後再定位對應結果。原稿仍可閱讀。', 'Body changes are pending. Save before locating the matching result. The original remains readable.'],
  immersivePreview: ['沉浸式预览', '沉浸式預覽', 'Expand document'],
  exitImmersive: ['退出沉浸模式', '退出沉浸模式', 'Exit expanded view'],
  documentVersions: ['文稿版本详情', '文稿版本詳情', 'Document version details'],
  documentWorkspace: ['文稿工作区', '文稿工作區', 'Document workspace'],
  documentInformation: ['文稿信息', '文稿資訊', 'Document information'],
  showEvidence: ['变量与证据', '變數與證據', 'Variables and evidence'],
  hideEvidence: ['收起变量与证据', '收起變數與證據', 'Hide variables and evidence'],
  savedBodyRevision: ['已保存版本', '已儲存版本', 'Saved revision'],
  pendingBodyRevision: ['正文有待保存修改', '正文有待儲存修改', 'Pending body changes'],
  pendingBodyNote: ['当前正文修改尚未写入已保存版本。保存正文后再查看对应 PDF 或导出。', '目前正文修改尚未寫入已儲存版本。儲存正文後再查看對應 PDF 或匯出。', 'The current body changes are not in the saved revision. Save the body before viewing its PDF or exporting.'],
  bodyReaderNote: ['先阅读正文，点击需要修改的段落再编辑。修改暂存于本页，点击“保存正文”后写入文稿；最终排版请切回 PDF 核对。', '先閱讀正文，點擊需要修改的段落再編輯。修改暫存於本頁，點擊「儲存正文」後寫入文稿；最終排版請切回 PDF 核對。', 'Read the document and select a paragraph to edit. Changes stay in this workspace until you save the body. Review the resulting layout in PDF.'],
  bodySearch: ['搜索条款或正文内容', '搜尋條款或正文內容', 'Search clauses or document text'],
  bodyEditParagraph: ['修改这一段', '修改這一段', 'Edit paragraph'],
  bodyDoneEditing: ['完成此段编辑', '完成此段編輯', 'Done editing'],
  bodyRestoreParagraph: ['恢复原文', '恢復原文', 'Restore original'],
  bodyModified: ['已修改', '已修改', 'Modified'],
  bodyAddedParagraphs: ['新增段落', '新增段落', 'Added paragraphs'],
  bodyOriginalText: ['修改前原文', '修改前原文', 'Original text'],
  bodyDraftText: ['本次修改文字', '本次修改文字', 'Your revised text'],
  bodyShowChanges: ['只看修改', '只看修改', 'Show changes only'],
  bodyShowAll: ['显示全部正文', '顯示全部正文', 'Show all paragraphs'],
  bodyNoMatches: ['没有匹配的段落。可清除搜索或显示全部正文。', '沒有符合的段落。可清除搜尋或顯示全部正文。', 'No matching paragraphs. Clear the search or show all paragraphs.'],
  bodyNoParagraphs: ['尚无可阅读的正文。', '尚無可閱讀的正文。', 'No document body is available.'],
  bodyEditDocument: ['正文编辑', '正文編輯', 'Edit document text'],
  bodySectionNavigation: ['条款导航', '條款導航', 'Clause navigation'],
  pdfJumpPage: ['跳转页码', '跳轉頁碼', 'Jump to page'],
  pdfZoomIn: ['放大', '放大', 'Zoom in'],
  pdfZoomOut: ['缩小', '縮小', 'Zoom out'],
  pdfFitWidth: ['适合宽度', '適合寬度', 'Fit width'],
  pdfZoom: ['缩放', '縮放', 'Zoom'],
  recordedModel: ['记录的模型', '記錄的模型', 'Recorded model'],
  profileIdentity: ['模型配置标识', '模型配置標識', 'Model configuration identity'],
  profileIdentityUnknown: ['没有保存模型配置标识；保留原记录的模型名称。', '沒有儲存模型配置標識；保留原記錄的模型名稱。', 'No saved profile identity; the original recorded model name is retained.'],
  profileIdentityNote: ['标识来自所选配置；尚无供应商对实际执行模型的独立证明。', '標識來自所選配置；尚無供應商對實際執行模型的獨立證明。', 'Configured profile; provider execution is not independently attested.'],
  bodyEditNote: ['逐段修改正文。新增段落可沿用当前段落的格式；原有制表符、分页及域保留，保存后请预览核对。', '逐段修改正文。新增段落可沿用目前段落的格式；原有製表符、分頁及欄位保留，儲存後請預覽核對。', 'Edit the body paragraph by paragraph. Added paragraphs inherit the selected paragraph format. Existing tabs, page breaks and fields are preserved; review the preview after saving.'],
  searchBody: ['搜索正文或段落编号', '搜尋正文或段落編號', 'Search body text or paragraph number'],
  paragraph: ['段落', '段落', 'Paragraph'],
  protectedBody: ['此段包含受保护的域或结构，请在 Word 原稿中修改后重新上传。', '此段包含受保護的欄位或結構，請在 Word 原稿中修改後重新上傳。', 'This paragraph contains protected fields or structure. Edit the source in Word and upload it again.'],
  insertParagraphs: ['在此段后新增段落', '在此段後新增段落', 'Add paragraphs after this paragraph'],
  newParagraphs: ['新增正文（每行一段）', '新增正文（每行一段）', 'Added body text (one paragraph per line)'],
  formatReview: ['文稿沿用上传的 Word 模板格式。PDF 字体替换、目录及页码域的刷新尚未认证，请核对最终预览。', '文稿沿用上傳的 Word 模板格式。PDF 字型替換、目錄及頁碼欄位的更新尚未認證，請核對最終預覽。', 'The draft uses the uploaded Word template format. PDF font substitutions and TOC/page-field refresh are unverified; review the final preview.'],
  editableSource: ['生成需要原始可编辑 DOCX 模板；修改模板后请上传修改后的 Word 文件。', '生成需要原始可編輯 DOCX 模板；修改模板後請上傳修改後的 Word 文件。', 'Generation requires the original editable DOCX templates. Upload the edited Word file after changing a template.'],
  title: ['合约文件起草', '合約文件起草', 'Contract drafting'],
  subtitle: ['读取资料，核对本次采用值，再预览及导出 NTT、SCT、SCC。', '讀取資料，核對本次採用值，再預覽及匯出 NTT、SCT、SCC。', 'Read sources, review the values adopted for this draft, then preview and export NTT, SCT and SCC.'],
  documents: ['1. 读取资料', '1. 讀取資料', '1. Read documents'],
  inputs: ['2. 核对起草输入', '2. 核對起草輸入', '2. Review drafting inputs'],
  preview: ['3. 预览及导出', '3. 預覽及匯出', '3. Preview and export'],
  templates: ['标准模板（2a）', '標準模板（2a）', 'Standard templates (2a)'],
  templateNote: ['模板提供需要回答的问题及修改指引。', '模板提供需要回答的問題及修改指引。', 'The templates establish the questions and editing guidance.'],
  uploadTemplates: ['上传并解析模板', '上傳並解析模板', 'Upload and parse templates'],
  replace: ['上传／替换', '上傳／替換', 'Upload / replace'],
  notUploaded: ['尚未上传', '尚未上傳', 'Not uploaded'],
  evidence: ['项目沟通资料', '項目溝通資料', 'Project correspondence'],
  evidenceNote: ['邮件、会议记录等资料提供候选值；未识别到的输入仍可人工填写。', '郵件、會議記錄等資料提供候選值；未識別到的輸入仍可人工填寫。', 'Emails and meeting records supply candidates. Unidentified inputs remain available for manual entry.'],
  uploadEvidence: ['上传起草资料', '上傳起草資料', 'Upload drafting evidence'],
  emptyEvidence: ['尚无项目资料，可先人工填写。', '尚無項目資料，可先人工填寫。', 'No correspondence uploaded. You can enter values manually.'],
  selectProject: ['请先选择或建立项目。', '請先選擇或建立項目。', 'Select or create a project first.'],
  manualEntry: ['人工填写', '人工填寫', 'Enter inputs manually'],
  extract: ['识别输入', '識別輸入', 'Identify inputs'],
  extracting: ['正在识别输入…', '正在識別輸入…', 'Identifying inputs…'],
  loading: ['正在读取资料…', '正在讀取資料…', 'Loading sources…'],
  uploading: ['正在上传及解析…', '正在上傳及解析…', 'Uploading and parsing…'],
  saving: ['正在保存本次采用值…', '正在儲存本次採用值…', 'Saving adopted values…'],
  generating: ['正在生成三份英文文稿…', '正在生成三份英文文稿…', 'Generating the three English drafts…'],
  exporting: ['正在导出…', '正在匯出…', 'Exporting…'],
  reviewIntro: ['人工修改优先。所有相关条款共享本次采用值；未知和待复核项保留标记，仍可生成草稿。', '人工修改優先。所有相關條款共享本次採用值；未知和待覆核項保留標記，仍可生成草稿。', 'Manual edits take precedence. Related clauses share one adopted value. Unknown and review items remain marked; you can still generate a draft.'],
  search: ['搜索问题、输入或条款', '搜尋問題、輸入或條款', 'Search questions, inputs or clauses'],
  reviewLayout: ['核对布局', '核對佈局', 'Review layout'],
  listLayout: ['A · 列表', 'A · 列表', 'A · List'],
  focusLayout: ['B · 逐题核对', 'B · 逐題核對', 'B · One question'],
  questionIndex: ['问题目录', '問題目錄', 'Question index'],
  previousQuestion: ['上一题', '上一題', 'Previous question'],
  nextQuestion: ['下一题', '下一題', 'Next question'],
  questionPosition: ['当前题目', '目前題目', 'Question'],
  all: ['全部状态', '全部狀態', 'All statuses'],
  missing: ['待补充', '待補充', 'Missing input'],
  suggested: ['待采用建议', '待採用建議', 'Suggested value'],
  adopted: ['已采用', '已採用', 'Adopted'],
  manual: ['人工采用', '人工採用', 'Manually adopted'],
  conflict: ['候选取值不一致', '候選取值不一致', 'Candidate values disagree'],
  latestExtraction: ['最近一次识别', '最近一次識別', 'Latest extraction'],
  intakeSuggested: ['有候选建议', '有候選建議', 'Suggestion returned'],
  candidateDisagreement: ['候选取值不一致', '候選取值不一致', 'Candidate values disagree'],
  candidateConflictNote: ['模型候选取值不一致；这不表示原始资料已确认存在冲突。请核对各项引文及取值。', '模型候選取值不一致；這不表示原始資料已確認存在衝突。請核對各項引文及取值。', 'Model candidate values disagree. This does not establish a conflict in the original sources. Review each quotation and value.'],
  intakeAccepted: ['通过接收校验', '通過接收校驗', 'Passed intake checks'],
  intakeRejected: ['候选未通过校验', '候選未通過校驗', 'Candidate rejected'],
  intakeUnanswered: ['模型未作答', '模型未作答', 'Model unanswered'],
  modelUnanswered: ['模型返回未定值', '模型回傳未定值', 'Model returned an unknown value'],
  noCandidate: ['模型未返回该字段', '模型未回傳該欄位', 'Model did not return this field'],
  sourceUnresolved: ['资料明确未决', '資料明確未決', 'Source explicitly leaves this unresolved'],
  sourceUnresolvedNote: ['原文明确表示待定或未提供；请核对以下理由和来源，仍可人工填写。', '原文明確表示待定或未提供；請核對以下理由和來源，仍可人工填寫。', 'The quoted source leaves this input pending or not supplied. Review the reason and source below; manual entry remains available.'],
  coverageUnresolved: ['直接资料线索补查后仍未识别', '直接資料線索補查後仍未識別', 'Direct source clue remains unresolved after a coverage check'],
  coverageUnresolvedNote: ['资料中有相关直接线索，但补查仍未取得可接受建议；请核对原文，不能据此认定资料没有答案。', '資料中有相關直接線索，但補查仍未取得可接受建議；請核對原文，不能據此認定資料沒有答案。', 'A direct source clue was found, but the coverage check returned no acceptable suggestion. Review the original source; this does not establish that it lacks an answer.'],
  notAssessed: ['本次尚未评估', '本次尚未評估', 'Not assessed in this run'],
  noUsableSuggestion: ['未返回可用建议；不能据此判断资料没有答案，仍可人工填写。', '未回傳可用建議；不能據此判斷資料沒有答案，仍可人工填寫。', 'No usable suggestion returned. This does not establish that the source lacks an answer. Manual entry remains available.'],
  intakeNotFact: ['通过接收校验仅表示格式及必要来源检查通过，取值仍需业务人员核对采用。', '通過接收校驗僅表示格式及必要來源檢查通過，取值仍需業務人員核對採用。', 'Passed intake checks means format and necessary source checks passed. Business facts still require review and adoption.'],
  diagnosticDetails: ['查看校验详情', '查看校驗詳情', 'Inspect intake details'],
  traceStale: ['识别后资料已变化；该报告对应旧资料版本，不代表当前输入的采用状态。', '識別後資料已變化；該報告對應舊資料版本，不代表目前輸入的採用狀態。', 'Sources have changed since this extraction. This report describes an earlier source revision, independently of current adoption.'],
  traceFailedNote: ['本次识别失败，已处理部分仅供诊断；原有采用值及建议独立保留。', '本次識別失敗，已處理部分僅供診斷；原有採用值及建議獨立保留。', 'This extraction failed. Assessed parts are diagnostic only; previous adopted values and suggestions remain independent.'],
  rawValue: ['模型原始取值', '模型原始取值', 'Raw model value'],
  normalizedValue: ['规范化候选值', '規範化候選值', 'Normalized candidate value'],
  unidentifiedKey: ['未提供字段键', '未提供欄位鍵', 'Field key not supplied'],
  attempt: ['调用', '呼叫', 'Attempt'],
  item: ['返回项', '回傳項', 'Item'],
  confidence: ['模型置信度', '模型置信度', 'Model confidence'],
  reasonUnknownKey: ['返回了目录以外的字段', '回傳了目錄以外的欄位', 'Field is outside the catalogue'],
  reasonHiddenKey: ['此字段不允许模型填写', '此欄位不允許模型填寫', 'This field is not available for model input'],
  reasonConfidenceMissing: ['模型未提供置信度', '模型未提供置信度', 'Model confidence was not supplied'],
  reasonConfidenceRange: ['模型置信度超出允许范围', '模型置信度超出允許範圍', 'Model confidence is outside the allowed range'],
  reasonConfidenceLow: ['模型置信度未达到接收阈值', '模型置信度未達到接收閾值', 'Model confidence is below the intake threshold'],
  reasonQuoteMissing: ['模型未提供来源引文', '模型未提供來源引文', 'Source quotation was not supplied'],
  reasonQuoteNotInPart: ['引文无法在本次实际资料片段中连续定位', '引文無法在本次實際資料片段中連續定位', 'Quotation could not be located contiguously in this source part'],
  reasonQuoteValueMismatch: ['引文不能支持该候选取值', '引文不能支持該候選取值', 'Quotation does not support the proposed value'],
  reasonBillMetadataUnsupported: ['缺乏依据的 Bill 元数据已从建议中移除', '缺乏依據的 Bill 元資料已從建議中移除', 'Unsupported Bill metadata was removed from the suggestion'],
  reasonSourceUnresolved: ['匹配的原文明确表示该输入未决', '匹配的原文明確表示該輸入未決', 'Matching source text explicitly leaves this input unresolved'],
  reasonValueShape: ['取值不符合要求的数据结构', '取值不符合要求的資料結構', 'Value does not match the required structure'],
  reasonUnanswered: ['模型返回空值或未定值', '模型回傳空值或未定值', 'Model returned an empty or unknown value'],
  reasonLiteralSupport: ['合约或清单的正式编号／名称未在该资料片段中找到', '合約或清單的正式編號／名稱未在該資料片段中找到', 'Formal contract or Bill identifier / description was not found in this source part'],
  reasonRepairKey: ['修复调用返回了未获准修复的字段', '修復呼叫回傳了未獲准修復的欄位', 'Repair returned a field outside the requested repair keys'],
  reasonCoverageKey: ['补查返回了目标字段以外的取值', '補查回傳了目標欄位以外的取值', 'Coverage check returned a field outside the requested keys'],
  reasonUnansweredRepairValue: ['未决项修复只允许校正来源引文，不能将未知值改成确定取值', '未決項修復只允許校正來源引文，不能將未知值改成確定取值', 'Unknown-source repair may correct the quotation, but cannot turn the unresolved input into a definite value'],
  reasonOther: ['其他诊断原因（详见代码及原始返回）', '其他診斷原因（詳見代碼及原始回傳）', 'Other diagnostic reason (inspect the code and raw response)'],
  needs_review: ['需复核', '需覆核', 'Review required'],
  inactive: ['本次不适用', '本次不適用', 'Not applicable to this draft'],
  prerequisite: ['前提未确定，仍可填写；本次适用性待核。', '前提未確定，仍可填寫；本次適用性待核。', 'The prerequisite is unresolved. You can enter a value while applicability is checked.'],
  hiddenFields: ['不适用的子项已隐藏，先前输入保留；条件恢复后可继续编辑。', '不適用的子項已隱藏，先前輸入保留；條件恢復後可繼續編輯。', 'Inapplicable follow-ups are hidden. Previous entries are retained and return when their conditions apply.'],
  optional: ['可选', '可選', 'optional'],
  unknown: ['请选择／尚未确定', '請選擇／尚未確定', 'Select / to be confirmed'],
  yes: ['是', '是', 'Yes'],
  no: ['否', '否', 'No'],
  addRow: ['添加项目', '新增項目', 'Add item'],
  remove: ['删除此项', '刪除此項', 'Remove item'],
  noItems: ['明确没有项目', '明確沒有項目', 'Confirm no items'],
  resetUnknown: ['恢复为未回答', '恢復為未回答', 'Reset to unanswered'],
  emptyConfirmed: ['已明确没有项目。', '已明確沒有項目。', 'No items confirmed.'],
  columns: ['项目详情', '項目詳情', 'Item details'],
  save: ['保存本次采用值', '儲存本次採用值', 'Save values for this draft'],
  saveInput: ['保存此项', '儲存此項', 'Save this input'],
  savingInput: ['保存中…', '儲存中…', 'Saving…'],
  savedInput: ['已保存', '已儲存', 'Saved'],
  saveInputFailed: ['保存失败，请重试', '儲存失敗，請重試', 'Save failed. Please retry.'],
  saveAll: ['保存所有修改', '儲存所有修改', 'Save all changes'],
  discard: ['放弃未保存修改', '放棄未儲存修改', 'Discard unsaved changes'],
  unsaved: ['有未保存修改', '有未儲存修改', 'Unsaved changes'],
  restoreNote: ['该项目的未保存修改已恢复。', '該項目的未儲存修改已恢復。', 'Unsaved changes for this project have been restored.'],
  sourceDetails: ['证据及相关条款', '證據及相關條款', 'Evidence and affected clauses'],
  sourceQuote: ['原文证据', '原文證據', 'Source evidence'],
  noSource: ['本次采用值未附来源引文。', '本次採用值未附來源引文。', 'No source quotation is attached to the adopted value.'],
  candidates: ['资料候选值', '資料候選值', 'Evidence candidates'],
  adoptCandidate: ['采用此候选值', '採用此候選值', 'Adopt this candidate'],
  reviewed: ['认可原值并完成复核', '認可原值並完成覆核', 'Retain this value and complete review'],
  adoptSuggested: ['采用当前建议', '採用目前建議', 'Adopt current suggestion'],
  trace: ['识别过程', '識別過程', 'Extraction trace'],
  reportSelection: ['识别报告', '識別報告', 'Extraction report'],
  latestReport: ['当前最近报告', '目前最近報告', 'Current latest report'],
  historicalReport: ['正在查看历史报告；仅供阅读，不会更改当前输入或采用状态。', '正在查看歷史報告；僅供閱讀，不會更改目前輸入或採用狀態。', 'Viewing a historical report. This is read-only and does not change current inputs or adoption.'],
  noTrace: ['尚无识别报告。', '尚無識別報告。', 'No extraction report is available.'],
  emptyTraceHistory: ['尚无已保存的历史报告。', '尚無已儲存的歷史報告。', 'No saved historical reports are available.'],
  traceHistoryUnavailable: ['历史报告暂时无法读取；仍可查看当前报告。', '歷史報告暫時無法讀取；仍可查看目前報告。', 'Historical reports could not be loaded. The current report remains available.'],
  traceHistoryBound: ['最多显示最近20次已保存报告。', '最多顯示最近20次已儲存報告。', 'Showing up to 20 recent saved reports.'],
  legacyTrace: ['此历史记录只保留提示词及原始返回，未记录逐字段校验原因；不能推断未识别字段的原因。', '此歷史記錄只保留提示詞及原始回傳，未記錄逐欄位校驗原因；不能推斷未識別欄位的原因。', 'This legacy trace contains prompts and raw responses without field intake decisions. Reasons for unidentified fields cannot be inferred.'],
  completedRun: ['识别完成', '識別完成', 'Extraction completed'],
  failedRun: ['识别失败', '識別失敗', 'Extraction failed'],
  sourceParts: ['资料片段及调用', '資料片段及呼叫', 'Source parts and attempts'],
  intakeRecordCounts: ['以上统计模型返回记录，包含不同资料和多次调用；不代表不同变量的数量。各输入的当前状态请查看输入卡片。', '以上統計模型回傳記錄，包含不同資料和多次呼叫；不代表不同變量的數量。各輸入的目前狀態請查看輸入卡片。', 'These counts describe model-return records across sources and attempts, not distinct inputs. Check each input card for its current status.'],
  sourcePart: ['片段', '片段', 'Part'],
  sourceHash: ['资料哈希', '資料雜湊', 'Source hash'],
  sourceDocumentId: ['资料编号', '資料編號', 'Source document ID'],
  sourcePartText: ['实际资料片段原文', '實際資料片段原文', 'Actual source part text'],
  primaryAttempt: ['主识别调用', '主識別呼叫', 'Primary extraction'],
  repairAttempt: ['定向修复调用', '定向修復呼叫', 'Targeted repair'],
  coverageAttempt: ['直接事实补查', '直接事實補查', 'Direct-fact coverage check'],
  recallAttempt: ['上下文补查', '上下文補查', 'Context recall'],
  recordedAttempt: ['记录的调用类型', '記錄的呼叫類型', 'Recorded attempt type'],
  contextPlan: ['资料上下文计划', '資料上下文計劃', 'Source context plan'],
  recordedContextText: ['记录的原文窗口（查看调用以确认是否提供）', '記錄的原文視窗（查看呼叫以確認是否提供）', 'Recorded original-source window (inspect the attempt to confirm submission)'],
  contextTrigger: ['上下文处理原因', '上下文處理原因', 'Context trigger'],
  contextJointOriginalPassage: ['为核对同一输入的证据关系而选取的原文及上下文。', '為核對同一輸入的證據關係而選取的原文及上下文。', 'Original passages and context selected to review evidence about the same input.'],
  contextKeys: ['目标输入', '目標輸入', 'Targeted inputs'],
  contextOffsets: ['原文位置（UTF-16，从0开始，不含结束位置）', '原文位置（UTF-16，從0開始，不含結束位置）', 'Original source offsets (UTF-16, zero-based, end excluded)'],
  suppliedContextText: ['本次实际提供的原文上下文', '本次實際提供的原文上下文', 'Actual supplied source context'],
  contextStopReason: ['补查停止原因', '補查停止原因', 'Recall stop reason'],
  recallCandidateFound: ['已找到有依据的建议；仍需人工核对及采用。', '已找到有依據的建議；仍需人工核對及採用。', 'A supported suggestion was found; human review and adoption are still required.'],
  recallNoSupportedCandidate: ['本次上下文未找到有依据的建议；可核对原文或人工填写。', '本次上下文未找到有依據的建議；可核對原文或人工填寫。', 'No supported suggestion was found in this context; review or enter the value manually.'],
  recallExplicitPending: ['原文明确将该输入留作待定。', '原文明確將該輸入留作待定。', 'The source explicitly leaves this input pending.'],
  recallContextInsufficient: ['可用上下文不足；该输入仍未解决。', '可用上下文不足；該輸入仍未解決。', 'The available context is insufficient; this input remains unresolved.'],
  recallBudgetExhausted: ['已达到补查预算上限；未决输入仍可人工填写。', '已達到補查預算上限；未決輸入仍可人工填寫。', 'The recall budget was reached; unresolved inputs remain available for manual entry.'],
  recallModelCallFailed: ['模型调用失败；不能据此认定资料没有答案。', '模型呼叫失敗；不能據此認定資料沒有答案。', 'The model call failed; this does not establish that the source lacks an answer.'],
  recallInvalidJson: ['模型返回无法解析；该输入仍未解决。', '模型回傳無法解析；該輸入仍未解決。', 'The response could not be parsed; this input remains unresolved.'],
  recallInactive: ['该输入本次不适用，已跳过补查；保留值未被清除。', '該輸入本次不適用，已跳過補查；保留值未被清除。', 'Recall was skipped because this input is currently inapplicable. Retained values were not cleared.'],
  recallNoSourceCue: ['未记录相关资料线索；不能据此认定资料没有答案。', '未記錄相關資料線索；不能據此認定資料沒有答案。', 'No related source cue was recorded; this does not establish that the source lacks an answer.'],
  recallUnknownStop: ['未记录此停止原因的说明；请查看原始代码及调用记录。', '未記錄此停止原因的說明；請查看原始代碼及呼叫記錄。', 'Stop description is not recorded; inspect the raw code and attempt record.'],
  contextOriginalNeighbors: ['已包含原文相邻上下文。', '已包含原文相鄰上下文。', 'Original neighboring source context was included.'],
  recallMissingOutput: ['主识别未返回该目标输入。', '主識別未回傳該目標輸入。', 'The primary extraction omitted the targeted input.'],
  recallOrdinaryNull: ['模型在相关资料线索旁返回未定值；不能据此认定原文明确待定。', '模型在相關資料線索旁回傳未定值；不能據此認定原文明確待定。', 'The model returned an unknown value beside a related source cue; this does not establish explicit source pending.'],
  recallRejectedCandidate: ['该资料中没有建议通过接收校验。', '該資料中沒有建議通過接收校驗。', 'No usable source-local suggestion passed intake checks.'],
  recallRelatedSource: ['原文明示引用另一份已上传资料。', '原文明示引用另一份已上傳資料。', 'An explicit reference points to another uploaded source.'],
  recallUnknownTrigger: ['未记录此触发原因的说明；请查看原始代码及调用记录。', '未記錄此觸發原因的說明；請查看原始代碼及呼叫記錄。', 'Trigger description is not recorded; inspect the raw code and attempt record.'],
  reasonRecallKey: ['上下文补查返回了目标字段以外的取值', '上下文補查回傳了目標欄位以外的取值', 'Context recall returned a field outside the requested keys'],
  reasonIncompleteSourceContext: ['提供的原文窗口截断了段落或表格；该片段不能确定完整替换文字或清单', '提供的原文視窗截斷了段落或表格；該片段不能確定完整替換文字或清單', 'The supplied source window cuts the paragraph or table; this fragment cannot establish a complete replacement or list'],
  attemptCompleted: ['调用完成', '呼叫完成', 'Attempt completed'],
  attemptFailed: ['调用失败', '呼叫失敗', 'Attempt failed'],
  attemptInvalid: ['返回格式未通过', '回傳格式未通過', 'Response format rejected'],
  runId: ['识别批次', '識別批次', 'Run ID'],
  startedAt: ['开始时间', '開始時間', 'Started at'],
  finishedAt: ['完成时间', '完成時間', 'Finished at'],
  evidenceRevision: ['资料版本', '資料版本', 'Evidence revision'],
  harnessVersion: ['识别流程版本', '識別流程版本', 'Harness version'],
  returnedItems: ['模型返回项', '模型回傳項', 'Returned model items'],
  rawResponses: ['模型原始返回', '模型原始回傳', 'Raw model responses'],
  systemPrompt: ['系统提示词', '系統提示詞', 'System prompt'],
  userPrompt: ['调用输入', '呼叫輸入', 'User prompt'],
  parsedStatus: ['已解析', '已解析', 'Parsed'],
  failedStatus: ['解析失败', '解析失敗', 'Parse failed'],
  waitingStatus: ['待解析', '待解析', 'Awaiting parsing'],
  affected: ['本次相关修改', '本次相關修改', 'Related changes for this draft'],
  noMatches: ['没有匹配的问题，可清除筛选。', '沒有符合的問題，可清除篩選。', 'No matching questions. Clear the filters.'],
  clearFilters: ['显示全部问题', '顯示全部問題', 'Show all questions'],
  generate: ['生成英文草稿', '生成英文草稿', 'Generate English drafts'],
  generateNote: ['未决项会随草稿列出。生成前会保存所有当前修改。', '未決項會隨草稿列出。生成前會儲存所有目前修改。', 'Unresolved items are recorded with the drafts. Current edits are saved before generation.'],
  missingTemplates: ['生成前请上传并成功解析 NTT、SCT、SCC 三份模板。', '生成前請上傳並成功解析 NTT、SCT、SCC 三份模板。', 'Upload and successfully parse all three templates before generation.'],
  backSources: ['返回资料', '返回資料', 'Back to documents'],
  backInputs: ['返回输入', '返回輸入', 'Back to inputs'],
  regenerate: ['重新生成', '重新生成', 'Regenerate'],
  stale: ['输入或资料已变化。这是先前生成稿；重新生成后才会应用本次变更。', '輸入或資料已變化。這是先前生成稿；重新生成後才會套用本次變更。', 'Inputs or sources have changed. This is the previous draft; regenerate to apply the current changes.'],
  staleReadOnly: ['先前文稿仅供阅读。请重新生成后再保存正文、查看 PDF 或导出。', '先前文稿僅供閱讀。請重新生成後再儲存正文、查看 PDF 或匯出。', 'The previous draft is read-only. Regenerate before saving content, previewing PDF or exporting.'],
  exportWord: ['导出 Word', '匯出 Word', 'Export Word'],
  exportPdf: ['导出 PDF', '匯出 PDF', 'Export PDF'],
  documentText: ['文稿正文', '文稿正文', 'Document content'],
  editContent: ['编辑正文', '編輯正文', 'Edit content'],
  viewPdf: ['查看 PDF', '查看 PDF', 'View PDF'],
  saveContent: ['保存正文及预览', '儲存正文及預覽', 'Save content and preview'],
  pdfLoading: ['正在加载 PDF…', '正在載入 PDF…', 'Loading PDF…'],
  pdfPages: ['PDF 页面导航', 'PDF 頁面導覽', 'PDF page navigation'],
  pdfPreviousPage: ['上一页', '上一頁', 'Previous page'],
  pdfNextPage: ['下一页', '下一頁', 'Next page'],
  pdfPage: ['页', '頁', 'Page'],
  pdfPageOf: ['／', '／', 'of'],
  pdfRenderFailed: ['PDF 页面未能显示，请重试；仍可查看正文或导出文件。', 'PDF 頁面未能顯示，請重試；仍可查看正文或匯出檔案。', 'The PDF page could not be displayed. Retry, view the content or export the file.'],
  pdfUnavailable: ['PDF 暂不可用，可查看正文或重试。', 'PDF 暫不可用，可查看正文或重試。', 'PDF is unavailable. View the content or retry.'],
  retry: ['重试', '重試', 'Retry'],
  regenerationNote: ['重新生成会替换三份文稿，包括已保存的正文修改。', '重新生成會取代三份文稿，包括已儲存的正文修改。', 'Regeneration replaces all three drafts, including saved content edits.'],
  unresolved: ['本次待核事项', '本次待核事項', 'Unresolved items in this draft'],
  jumpInput: ['返回相关输入', '返回相關輸入', 'Go to related input'],
  exactEdit: ['对该目标采用人工修改', '對該目標採用人工修改', 'Adopt a manual change for this target'],
  targetAction: ['修改动作', '修改動作', 'Editing action'],
  targetText: ['本次采用的精确英文文本', '本次採用的精確英文文字', 'Exact English text adopted for this draft'],
  sourceMapping: ['来源／版次对应及判断依据', '來源／版次對應及判斷依據', 'Source / edition mapping and decision basis'],
  sourceMappingNote: ['引用或版次待核目标，需要说明本次采用的实际条款位置及依据。', '引用或版次待核目標，需要說明本次採用的實際條款位置及依據。', 'For a reference or edition check, record the actual adopted clause position and the supporting basis.'],
  sourceTarget: ['展开当前目标原文', '展開目前目標原文', 'Expand source target'],
  sourceWarning: ['原始来源／版次警告', '原始來源／版次警告', 'Original source / edition warning'],
  billDistribution: ['由当前取值联动的发放安排', '由目前取值聯動的發放安排', 'Issue distribution linked to current inputs'],
  distributionNote: ['此表使用上方共享清单，修改投标方式即可联动；正式说明及手填安排保留。保存后用于本次生成。', '此表使用上方共享清單，修改投標方式即可聯動；正式說明及手填安排保留。儲存後用於本次生成。', 'This view uses the shared list above and updates when the issue format changes. Formal descriptions and custom wording are retained. Save changes for generation.'],
  l10Notice: ['L10Pro：BQ Bill 1／2 的正文置于 Disc A，Collection／Summary 页置于 Disc B；其他标准 BQ 置于 Disc B。', 'L10Pro：BQ Bill 1／2 的正文置於 Disc A，Collection／Summary 頁置於 Disc B；其他標準 BQ 置於 Disc B。', 'L10Pro: BQ Bills 1 / 2 use Disc A for their bodies and Disc B for Collection / Summary pages; other standard BQ Bills use Disc B.'],
  hardcopyNotice: ['纸本：BQ Bill 2 置于 Disc A；Bill 1及其他 BQ 发放纸本并在 Disc C 提供 Excel 副本。', '紙本：BQ Bill 2 置於 Disc A；Bill 1及其他 BQ 發放紙本並在 Disc C 提供 Excel 副本。', 'Hardcopy: BQ Bill 2 uses Disc A; Bill 1 and other BQ Bills use hardcopy with Excel companions on Disc C.'],
  unknownIssueNotice: ['先选择 BQ 发放方式。未知不代表纸本，SOR 安排仍独立判断。', '先選擇 BQ 發放方式。未知不代表紙本，SOR 安排仍獨立判斷。', 'Select the BQ issue format. Unknown does not mean paper, and SOR arrangements are decided independently.'],
  discA: ['Disc A · PDF', 'Disc A · PDF', 'Disc A · PDF'],
  discB: ['Disc B · 已填写的分发安排', 'Disc B · 已填寫的分發安排', 'Disc B · entered placement'],
  discBL10Pro: ['Disc B · L10Pro／采用安排', 'Disc B · L10Pro／採用安排', 'Disc B · L10Pro / adopted arrangement'],
  discBHardcopy: ['Disc B · 纸本模式原文用于 Drawings', 'Disc B · 紙本模式原文用於 Drawings', 'Disc B · drawings in the hardcopy source provisions'],
  sourceAmendmentRequired: ['需复核／需修改来源条款', '需覆核／需修改來源條款', 'Review / source amendment required'],
  hardcopyDiscBReview: ['纸本模式的原文将 Disc B 用于 Drawings。此计价文件的 Disc B 输入已保留；采用前须对 SCT1／相关来源目标作精确人工改文，不能视作标准纸本安排。', '紙本模式的原文將 Disc B 用於 Drawings。此計價文件的 Disc B 輸入已保留；採用前須對 SCT1／相關來源目標作精確人工改文，不能視作標準紙本安排。', 'The hardcopy source provisions use Disc B for drawings. This pricing-document placement is retained, but requires an exact adopted amendment to SCT1 / the relevant source target before use; it is not the standard hardcopy arrangement.'],
  l10HardcopyReview: ['L10Pro 模式下此项目改用纸本发放，属于项目特定安排。输入已保留，须核对并对 SCT1／相关来源目标作精确人工改文。', 'L10Pro 模式下此項目改用紙本發放，屬於項目特定安排。輸入已保留，須核對並對 SCT1／相關來源目標作精確人工改文。', 'Issuing this item in hardcopy under L10Pro is a project-specific arrangement. The entry is retained; review and adopt an exact amendment to SCT1 / the relevant source target.'],
  customPlacementReview: ['项目特定分发原文已保留；本清单不会自动完成条款改写。须核对并对 SCT1／相关来源目标采用精确人工改文。', '項目特定分發原文已保留；本清單不會自動完成條款改寫。須核對並對 SCT1／相關來源目標採用精確人工改文。', 'The project-specific distribution wording is retained. Entering it in this list does not complete the source amendment. Review and adopt an exact amendment to SCT1 / the relevant source target.'],
  hardcopy: ['纸本计价文件', '紙本計價文件', 'Hardcopy pricing documents'],
  discC: ['Disc C · Excel 副本', 'Disc C · Excel 副本', 'Disc C · Excel companion'],
  custom: ['项目特定安排（原文）', '項目特定安排（原文）', 'Project-specific arrangement (exact wording)'],
  billNumber: ['Bill／Schedule编号', 'Bill／Schedule編號', 'Bill / Schedule number'],
  billDescription: ['正式说明', '正式說明', 'Formal description'],
  issueParts: ['发放部分', '發放部分', 'Issued parts'],
  bodyWithoutTotals: ['正文，不含 Collection 及 Summary 页', '正文，不含 Collection 及 Summary 頁', 'Body, excluding Collection and Summary pages'],
  totalsOnly: ['仅 Collection 及 Summary 页', '僅 Collection 及 Summary 頁', 'Collection and Summary pages only'],
  wholeBq: ['标准纸本 BQ', '標準紙本 BQ', 'Standard hardcopy BQ'],
  excelCompanion: ['Excel 编价副本；Bill 2不在此安排', 'Excel 編價副本；Bill 2不在此安排', 'Excel pricing companion; Bill 2 is excluded'],
  preamblesPdf: ['电子投标册中的 Preambles', '電子投標冊中的 Preambles', 'Preambles in the electronic tender booklet'],
  l10Bq: ['标准 L10Pro BQ', '標準 L10Pro BQ', 'Standard L10Pro BQ'],
  adoptedPlacement: ['已采用的独立安排；核对相应正文／汇总页范围', '已採用的獨立安排；核對相應正文／匯總頁範圍', 'Independently adopted placement; check the corresponding body / totals scope'],
  sorPlacementPending: ['SOR 的实际发放／补遗安排待采用，不能从名称或 BQ 方式推断', 'SOR 的實際發放／補遺安排待採用，不能從名稱或 BQ 方式推斷', 'Adopt the actual SOR issue / addenda arrangement; it cannot be inferred from its name or the BQ format'],
  pricingTypePending: ['待确定 BQ 或 SOR 类型，未推断分发位置', '待確定 BQ 或 SOR 類型，未推斷分發位置', 'Confirm BQ or SOR type; no placement has been inferred'],
  issuePending: ['BQ 发放方式待确定', 'BQ 發放方式待確定', 'BQ issue format is unresolved'],
  customPlacementPending: ['请补充项目特定分发原文', '請補充項目特定分發原文', 'Enter the exact project-specific distribution wording'],
  billRolePending: ['该项目说明与标准 Bill 用途未对齐，请核对；原说明保留。', '該項目說明與標準 Bill 用途未對齊，請核對；原說明保留。', 'The project description is not aligned with the standard Bill role. Verify it; the original description is retained.'],
  generalSummary: ['标准安排也包含 General Summary。', '標準安排也包含 General Summary。', 'The standard arrangement also includes the General Summary.'],
  l10Return: ['SCT3：印出并填写 Bill 1 PDF 正文，将页总数填入 L10Pro；按要求交回已编价纸本、General Summary 及加密电子价格文件。', 'SCT3：印出並填寫 Bill 1 PDF 正文，將頁總數填入 L10Pro；按要求交回已編價紙本、General Summary 及加密電子價格檔案。', 'SCT3: print and price the Bill 1 PDF body, enter page totals in L10Pro, and return the required printed priced Bills, General Summary and encrypted price file.'],
  paperReturn: ['SCT3：填写并交回原纸本 Bills／General Summary，同时在 DVD-ROM 提交已编价 Excel；电子副本不代替纸本交回。', 'SCT3：填寫並交回原紙本 Bills／General Summary，同時在 DVD-ROM 提交已編價 Excel；電子副本不代替紙本交回。', 'SCT3: price and return the original hardcopy Bills / General Summary with priced Excel files on DVD-ROM. The electronic copy does not replace the required hardcopy return.'],
  customReturnReview: ['SCT3 标准交回要求仍需与本次投标制度及自定义 SCT5 对齐。', 'SCT3 標準交回要求仍須與本次投標制度及自訂 SCT5 對齊。', 'Reconcile the standard SCT3 return requirements with the adopted tendering system and any custom SCT5.'],
  targetNote: ['人工修改用于该目标；原文未能定位等来源问题仍须核对，不能自动消除。', '人工修改用於該目標；原文未能定位等來源問題仍須核對，不能自動消除。', 'The manual change applies to this target. Source or anchor warnings still require review.'],
  targetSave: ['保存并采用目标修改', '儲存並採用目標修改', 'Save and adopt target change'],
  targetReset: ['取消此人工覆盖', '取消此人工覆蓋', 'Remove this manual override'],
  retain: ['保留', '保留', 'Retain'],
  amend: ['改写／填写', '改寫／填寫', 'Amend / fill'],
  delete: ['删除', '刪除', 'Delete'],
  not_used: ['标记 Not used', '標記 Not used', 'Mark Not used'],
  not_adopted: ['本次不采用', '本次不採用', 'Not adopted'],
  pending: ['待核', '待核', 'Pending'],
  invalid: ['取值格式需核对；输入已保留。', '取值格式需核對；輸入已保留。', 'Review the value format. Your entry is retained.'],
  incomplete: ['请核对各项必要内容。', '請核對各項必要內容。', 'Check the required details of each item.'],
  duplicate: ['编号重复；保留记录并请核对实际对象。', '編號重複；保留記錄並請核對實際對象。', 'Duplicate identifiers: the records are retained. Verify the actual items.'],
  negative: ['金额／数量不能为负，请核对。', '金額／數量不能為負，請核對。', 'Amounts / quantities cannot be negative. Review the entry.'],
  reversedDates: ['开始日期晚于结束日期，请复核；已保留输入。', '開始日期晚於結束日期，請覆核；已保留輸入。', 'The start date is later than the end date. Review the dates; your entries are retained.'],
  durationDerived: ['该判断由已填写的工期派生，39个月含等号。清空实际工期后可直接回答阈值。', '該判斷由已填寫的工期派生，39個月含等號。清空實際工期後可直接回答閾值。', 'This answer follows the entered duration; exactly 39 months qualifies. Clear the optional duration to answer the threshold directly.'],
  durationConflict: ['工期与已采用的39个月阈值不同，请由业务人员核对；人工值保留。', '工期與已採用的39個月閾值不同，請由業務人員核對；人工值保留。', 'The duration and adopted 39-month threshold differ. Review the basis; the manual value is retained.'],
  number: ['合约编号', '合約編號', 'Contract number'],
  contractTitle: ['合约名称', '合約名稱', 'Contract title'],
  ruleVersion: ['规则版本', '規則版本', 'Rule version'],
  snapshot: ['生成快照', '生成快照', 'Generation snapshot'],
  unsavedLeave: ['有未保存的起草修改。', '有未儲存的起草修改。', 'There are unsaved drafting changes.'],
  parsed: ['份资料已解析', '份資料已解析', 'files parsed'],
  removeCorrespondence: ['移除资料', '移除資料', 'Remove correspondence'],
  removeCorrespondenceNote: ['从本项目当前资料中移除；原始文件保留存档。受此来源影响的取值需要复核。', '從本項目目前資料中移除；原始檔案保留存檔。受此來源影響的取值需要覆核。', 'Remove from this project’s active correspondence. The original file is retained in the archive. Values linked to this source require review.'],
  removeFromProject: ['从项目移除', '從項目移除', 'Remove from project'],
  close: ['关闭', '關閉', 'Close'],
  reasonUnsupportedEmptyList: ['引文及原始上下文不能证明没有适用项目；这条空清单未被接收。补查仍无依据时保持未定，可人工填写及采用。', '引文及原始上下文不能證明沒有適用項目；這條空清單未被接收。補查仍無依據時保持未定，可人工填寫及採用。', 'The quotation and its original context do not establish that there are no applicable items. This empty list was not accepted. If bounded recall finds no support, the input remains unknown and available for human entry and adoption.'],
  emptyListSuggestion: ['空清单建议：没有适用项目。仍须核对原文并人工采用。', '空清單建議：沒有適用項目。仍須核對原文並人工採用。', 'Empty-list suggestion: no applicable items. Review the original source and adopt manually.'],
  templateReading: ['模板条款预览', '模板條款預覽', 'Template reading preview'],
  locateTemplate: ['查看模板位置', '查看模板位置', 'Locate in template'],
  editPreviewValue: ['修改本次取值', '修改本次取值', 'Edit value for this draft'],
  previewEditNote: ['这里与输入清单共享取值。手工修改保存后用于本次起草；模型建议仍需人工采用。已生成文稿需重新生成。', '這裡與輸入清單共享取值。手工修改儲存後用於本次起草；模型建議仍須人工採用。已生成文稿須重新生成。', 'This editor shares the input list’s values. Saved manual changes apply to this draft; suggestions require adoption. Existing documents require regeneration.'],
  unsavedValue: ['未保存修改', '未儲存修改', 'Unsaved change'],
} as const

export type DraftWord = keyof typeof triples
export function draftWord(key: DraftWord, locale: AppLocale): string { return triples[key][locale === 'en' ? 2 : locale === 'zh-Hant' ? 1 : 0] }
export function localized(text: LocalizedText | string | undefined | null, locale: AppLocale): string {
  if (!text) return ''
  if (typeof text === 'string') return text
  return text[locale === 'en' ? 'en' : locale === 'zh-Hant' ? 'zhHant' : 'zhHans'] || text.en || text.zhHans || ''
}
